global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [localhost:9090]
  - job_name: "otel-collector"
    static_configs:
      - targets: [otel-collector:9201]
